# Generated by Django 5.1.3 on 2024-11-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='email_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
