# Generated by Django 5.1.3 on 2024-11-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='user',
        ),
    ]
